### ISSUE TITLE
Error in init$Extract(string = word, sequence_strings = choices, processor = PROC,  :    attempt to apply non-function

### ISSUE THREAD

**Issue by EnricowithR** [mlampros/fuzzywuzzyR#2]
Hi,

if I try to run your example, the code is below, I get the following error:
"Error in init$Extract(string = word, sequence_strings = choices, processor = PROC,  : 
  attempt to apply non-function"

I tried with both package versions, the one in Cran and in Github.

This is the code which generates that error:

library(fuzzywuzzyR)
word = "new york jets"

choices = c("Atlanta Falcons", "New York Jets", "New York Giants", "Dallas Cowboys")

# processor :
init_proc = FuzzUtils$new()      # initialization of FuzzUtils class to choose a processor

PROC = init_proc$Full_process    # processor-method

PROC1 = tolower                  # base R function ( as an example for a processor )

# scorer :
init_scor = FuzzMatcher$new()    # initialization of the scorer class

SCOR = init_scor$WRATIO          # choosen scorer function

init <- FuzzExtract$new()  
# Initialization of the FuzzExtract class
init$Extract(string = word, sequence_strings = choices, processor = PROC, scorer = SCOR)

**Comment by mlampros** [comment]
@EnricowithR another user of the fuzzywuzzyR package had a similar issue. Please, take a look [here](https://github.com/mlampros/fuzzywuzzyR/issues/1).

**Comment by mlampros** [comment]
@EnricowithR I'll close the issue for now, feel free to reopen it if the mentioned link won't solve your issue.

**Comment by JakeSavoca** [comment]
I am getting the same error. Were you able to figure out how to fix it?
