### ISSUE TITLE
Attempt to apply non-function

### ISSUE THREAD

**Issue by lolasbond** [mlampros/fuzzywuzzyR#5]
The package used to work well (just 3 months ago in fact), but recently, when I use parts of it, I'm getting this error:

Error in DIFFLIB$get_close_matches(string, sequence_strings, n, cutoff) : 
  attempt to apply non-function

I do have python installed, as well as all the other dependencies, and it worked 3 months ago (I had no issues then).

Here's my output for reticulate::py_discover_config(required_module = 'fuzzywuzzy') in case that helps:

python:         C:\Users\username\AppData\Local\Programs\Python\Python36\python.exe
libpython:      C:/Users/username/AppData/Local/Programs/Python/Python36/python36.dll
pythonhome:     C:\Users\username\AppData\Local\Programs\Python\Python36
version:        3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy
numpy_version:  1.14.5
fuzzywuzzy:     C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\fuzzywuzzy\__init__.p

python versions found: 
 C:\Users\username\AppData\Local\Programs\Python\Python36\python.exe
 C:\Users\username\AppData\Local\Programs\Python\Python36\\python.exe

What might be happening?  Thanks!

**Comment by mlampros** [comment]
hi @lolasbond,

just for your information the 'fuzzywuzzyR' package imports the 'reticulate' package which is necessary for the interface between python and R. It might be the case that a similar issue appeared in the past in the [reticulate issues](https://github.com/rstudio/reticulate/issues) as well.

What I'll write is just an assumption based on the output of your

```R

reticulate::py_discover_config(required_module = 'fuzzywuzzy')

```

It seems that you have 2 python 3.6 versions installed (*python versions found:*). You probably have installed the 'fuzzywuzzyR' package in one of both versions, which however is currently not your default version when you try to use Python from within the R console (via the reticulate package).

**Comment by lolasbond** [comment]
Thank you!  That does seem to have solved the issue.
