### ISSUE TITLE
R Studio crashes when trying to use dplyr and fuzzywuzzyR at the same time.

### ISSUE THREAD

**Issue by clandinq** [mlampros/fuzzywuzzyR#6]
R Studio crashes when trying to use dplyr and fuzzywuzzyR at the same time. 
Simple example:
library(fuzzywuzzyR)
library(dplyr)
--> R Session Aborted. 
--> R encountered a fatal error.
--> The session was terminated.

**Comment by mlampros** [comment]
Hi @clandinq,

can you add a minimal reproducible example and share a bit more information about your system configuration:
* Python version (2 or 3)
* Operating system (Linux, Macintosh, Windows)
* R version
* FuzzywuzzyR version
* dplyr version

thanks for reporting this issue.
